version: '3'

services:

#   MARIADB CONFIG
  mariadb :
    container_name: mariadb
    hostname: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env

#   WORDPRESS CONFIG
  wordpress :
    depends_on:
      - mariadb
    container_name: wordpress
    hostname: wordpress
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file: .env

#   NGINX CONFIG
  nginx :
    depends_on:
      - mariadb
      - wordpress
    container_name: nginx
    hostname: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file: .env

#   NETWORKS
networks:
  inception:
    driver: bridge

  # VOLUMES
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/larlena/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/larlena/data/mariadb
