version: '3'

services:

#   MARIADB CONFIG
  mariadb :
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: always
    volumes:
      - ~/data/mariadb:/var/lib/mariadb
    env_file: .env

#   WORDPRESS CONFIG
  wordpress :
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - "8080:80"
    networks:
      - backend
      - frontend
    restart: always
    volumes:
      - ~/data/wordpress:/var/www/html

#   NGINX CONFIG
  nginx :
    depends_on:
      - mariadb
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    restart: always
    volumes:
      - ~/data/wordpress:/var/www/html
    env_file: .env

#   NETWORKS
networks:
  frontend:
  backend:

#   VOLUMES
# volumes:
#   wordpress:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/${USER}/data/wordpress
#   mariadb:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/${USER}/data/mariadb
